version: "3"

services:
  broker:
    build:
      context: ./broker
      dockerfile: ./Dockerfile
    image: broker
    container_name: broker
    restart: always
    ports:
      - 8080:80
    deploy:
      mode: replicated
      replicas: 1
