version: "3"

services:
  broker:
    build:
      context: ./broker
      dockerfile: ./Dockerfile
    image: broker
    container_name: broker
    restart: always
    ports:
      - 8080:80
    deploy:
      mode: replicated
      replicas: 1

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    image: frontend
    container_name: frontend
    restart: always
    ports:
      - 3000:3000
